import {
  heroHome,
  heroHeart,
  heroCalendarDays,
  heroUserCircle,
  heroClipboardDocumentList,
  heroMagnifyingGlass,
  heroArrowRightStartOnRectangle,
  heroEye,
  heroXMark,
  heroAdjustmentsHorizontal,
  heroFolder,
  heroPhoto,
  heroPlus,
  heroCheck,
  heroCheckCircle,
  heroXCircle,
  heroClock,
  heroChevronLeft,
  heroPencilSquare,
  heroExclamationTriangle,
  heroArrowLeft,
} from '@ng-icons/heroicons/outline';

export const appIcons = {
  heroHome,
  heroHeart,
  heroCalendarDays,
  heroUserCircle,
  heroClipboardDocumentList,
  heroMagnifyingGlass,
  heroArrowRightStartOnRectangle,
  heroEye,
  heroXMark,
  heroAdjustmentsHorizontal,
  heroFolder,
  heroPhoto,
  heroPlus,
  heroCheck,
  heroCheckCircle,
  heroXCircle,
  heroClock,
  heroChevronLeft,
  heroPencilSquare,
  heroExclamationTriangle,
  heroArrowLeft,
};
